-- Create daily_picks table for storing Gary's picks
CREATE TABLE IF NOT EXISTS daily_picks (
  id SERIAL PRIMARY KEY,
  date DATE NOT NULL UNIQUE,
  picks JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add Row Level Security (RLS) policies for daily_picks table
ALTER TABLE daily_picks ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anyone to select picks
CREATE POLICY "Anyone can read picks" 
  ON daily_picks FOR SELECT USING (true);
  
-- Create policy to allow authenticated users to insert/update picks
CREATE POLICY "Authenticated users can create and update picks" 
  ON daily_picks FOR INSERT 
  WITH CHECK (auth.role() = 'authenticated' OR auth.role() = 'anon');
  
CREATE POLICY "Authenticated users can update picks" 
  ON daily_picks FOR UPDATE 
  USING (auth.role() = 'authenticated' OR auth.role() = 'anon');

-- Create index on date for faster lookups
CREATE INDEX idx_daily_picks_date ON daily_picks(date);

-- Comment on table and columns for clarity
COMMENT ON TABLE daily_picks IS 'Stores daily sports picks generated by Gary';
COMMENT ON COLUMN daily_picks.date IS 'Date for which picks are valid in YYYY-MM-DD format';
COMMENT ON COLUMN daily_picks.picks IS 'JSON array of pick objects with game data, analysis, and betting information';
