import {beforeEach,describe,it,expect,vi} from 'vitest';
const context=vi.hoisted(()=>({getNcaafGameContext:vi.fn()}));
vi.mock('../../../src/services/ncaafGameContext.js',()=>context);
const ledger=vi.hoisted(()=>({gamesWithRowsToday:vi.fn(async()=>new Set())}));
vi.mock('../../../src/services/insights/ncaafLaneLedger.js',async original=>({...await original(),...ledger}));
const{computeNcaafQbWatch}=await import('../../../src/services/insights/computers/ncaafQbWatch.js');
const game={id:99,date:'2026-09-19T20:00:00Z',home_team:{id:1,abbreviation:'H'},visitor_team:{id:2,abbreviation:'A'}};
const side=(name,id,status='confirmed')=>({quarterback:{name,player_id:id,status,sources:['s']},sources:[{id:'s',url:'https://school.edu/depth'}]});
let ctx;
beforeEach(()=>{vi.clearAllMocks();ledger.gamesWithRowsToday.mockResolvedValue(new Set());context.getNcaafGameContext.mockResolvedValue({observed_at:'2026-09-19T12:00:00Z',sides:{home:side('Starter H',10),away:side('Starter A',20,'projected')}});ctx={league:'ncaaf',date:'2026-09-19',season:2026,games:[game],helpers:{gameLabel:()=> 'A @ H'},bdl:{getNcaafPlayerGameStats:vi.fn(async()=>[])}};});
const stat=(id,teamId,season=2026)=>({player:{id},team:{id:teamId,abbreviation:'OLD'},season,game:{id:11+id,date:`${season}-09-05T20:00:00Z`,season,status:'Final'},passing_attempts:20,passing_completions:12,passing_yards:200,passing_touchdowns:2,passing_interceptions:0});
describe('named college starting quarterbacks',()=>{
 it('shows both reported starters even on a debut with no stats',async()=>{const rows=await computeNcaafQbWatch(ctx);expect(rows).toHaveLength(2);expect(rows.map(r=>r.meta.qb_status)).toEqual(['projected','confirmed']);expect(rows.every(r=>r.meta.passing===null)).toBe(true);expect(rows[0].detail).toContain('No verified passing sample');});
 it('stats describe the named starter, never the higher-volume backup',async()=>{ctx.bdl.getNcaafPlayerGameStats.mockImplementation(async({season})=>season===2026?[stat(10,1),{...stat(30,1),passing_attempts:90}]:[]);const rows=await computeNcaafQbWatch(ctx);const home=rows.find(r=>r.meta.side==='home');expect(home.player_id).toBe(10);expect(home.meta.passing).toMatchObject({yards:200,attempts:20,season:2026,prior:false});expect(home.headline).toContain('confirmed starter');expect(ctx.bdl.getNcaafPlayerGameStats.mock.calls[0][0].playerIds).toEqual([20,10]);});
 it('labels prior-season transfer stats and does not claim a current sample',async()=>{ctx.bdl.getNcaafPlayerGameStats.mockImplementation(async({season,playerIds})=>season===2025&&playerIds[0]===20?[stat(20,9,2025)]:[]);const away=(await computeNcaafQbWatch(ctx)).find(r=>r.meta.side==='away');expect(away.detail).toContain('2025 prior-season');expect(away.detail).toContain('for OLD');expect(away.meta.passing.prior).toBe(true);});
 it('does not turn missing fields into zero stats',async()=>{ctx.bdl.getNcaafPlayerGameStats.mockResolvedValue([{...stat(10,1),passing_touchdowns:null}]);const home=(await computeNcaafQbWatch(ctx)).find(r=>r.meta.side==='home');expect(home.meta.passing).toBeNull();});
 it('requires both named sides in the completion ledger',async()=>{await computeNcaafQbWatch(ctx);expect(ledger.gamesWithRowsToday).toHaveBeenCalledWith(expect.objectContaining({source:'ncaaf_game_context_v1',requireBothSides:true}));});
 it('does not guess when reporting is unresolved or unavailable',async()=>{context.getNcaafGameContext.mockResolvedValue({unavailable:true});expect(await computeNcaafQbWatch(ctx)).toEqual([]);});
 it('does not run for NFL or already completed games',async()=>{expect(await computeNcaafQbWatch({...ctx,league:'nfl'})).toEqual([]);ledger.gamesWithRowsToday.mockResolvedValue(new Set(['99']));expect(await computeNcaafQbWatch(ctx)).toEqual([]);expect(context.getNcaafGameContext).not.toHaveBeenCalled();});
});
