import { describe, it, expect, vi } from 'vitest';
import { getNcaafGameContext, validateCollegeContext, parseCollegeContext, searchSourceTrace } from '../../src/services/ncaafGameContext.js';
const player=(id,name,position='QB')=>({id,full_name:name,position});
const setup=()=>{
 const game={id:99,home_team:{id:1,full_name:'Home'},visitor_team:{id:2,full_name:'Away'}};
 const sources=[{id:'s',url:'https://school.edu/report',reported:'2026-09-18'}];
 const side=(id,name)=>({team_id:id,availability:'checked',quarterback:{name,status:'confirmed',sources:['s']},injuries:[],sources,coaches:[{name:'Current Coach',role:'head coach',sources:['s']}],context:[]});
 return {raw:{home:side(1,'Home QB'),away:side(2,'Away QB')},opts:{game,date:'2026-09-19',now:'2026-09-19T12:00:00Z',rosters:{home:[player(10,'Home QB'),player(11,'Home RB','RB')],away:[player(20,'Away QB')]},sourceRecord:[{type:'web_search_tool_result',content:[{type:'web_search_result',url:sources[0].url}]}]}};
};
describe('college context evidence boundary',()=>{
 it('repairs malformed structured output once without promoting prose into starter confirmation',async()=>{const{raw,opts}=setup();const search=vi.fn(async()=>({success:true,data:'Reports incomplete; injuries unknown.',raw:opts.sourceRecord}));const repair=vi.fn(async()=>raw);const result=await getNcaafGameContext({game:opts.game,date:opts.date,bdl:{},rosters:opts.rosters,cache:{enabled:false},search,repair});expect(search).toHaveBeenCalledTimes(1);expect(repair).toHaveBeenCalledTimes(1);expect(result.sides.home.quarterback).toBeNull();expect(result.sides.away.quarterback).toBeNull();expect(result.reason).toContain('could not be verified');});
 it('rejects a fabricated recent date on an old retrieved search result',()=>{const{raw,opts}=setup();opts.sourceRecord[0].content[0].page_age='3 months ago';expect(validateCollegeContext(raw,opts).unavailable).toBe(true);});
 it('does not repeat an old QB eligibility claim as current when current reporting cannot verify the starter',()=>{const{raw,opts}=setup();raw.home.quarterback={name:null,status:'unresolved',note:'Old eligibility allegation',sources:['old']};raw.home.sources.push({id:'old',url:'https://school.edu/old',reported:'2026-08-01'});const result=validateCollegeContext(raw,opts);expect(result.unavailable).toBe(true);expect(result.sides.home.quarterback).toBeNull();expect(result.sides.home.quarterback_uncertainty).toContain('could not be verified');expect(JSON.stringify(result)).not.toContain('Old eligibility allegation');});
 it('parses actual grounded transport prose surrounding JSON',()=>{const{raw}=setup();expect(parseCollegeContext('Research\n```json\n'+JSON.stringify(raw)+'\n```')).toEqual(raw);expect(parseCollegeContext('No report')).toBeNull();});
 it('requires dated sources and roster identities for both teams',()=>{const{raw,opts}=setup();expect(validateCollegeContext(raw,opts)).toMatchObject({unavailable:false,sides:{home:{quarterback:{player_id:10,status:'confirmed'}},away:{quarterback:{player_id:20}}}});});
 it.each(['invented','stale','future','wrong team','non QB'])('rejects %s starter evidence',kind=>{const{raw,opts}=setup();if(kind==='invented')opts.sourceRecord=[];if(kind==='stale')raw.home.sources[0].reported='2025-09-18';if(kind==='future')raw.home.sources[0].reported='2026-09-20';if(kind==='wrong team')raw.home.team_id=2;if(kind==='unresolved')raw.home.quarterback.status='unresolved';if(kind==='non QB')raw.home.quarterback.name='Home RB';const result=validateCollegeContext(raw,opts);expect(result.unavailable).toBe(true);expect(result.sides.home.quarterback).toBeNull();});
 it('keeps a projected starter distinct and rejects ambiguity',()=>{const{raw,opts}=setup();raw.home.quarterback.status='projected';expect(validateCollegeContext(raw,opts).sides.home.quarterback.status).toBe('projected');opts.rosters.home.push(player(12,'Home QB'));expect(validateCollegeContext(raw,opts).sides.home.quarterback).toBeNull();});
 it('does not treat a bad injury identity or unavailable search as a healthy team',()=>{const{raw,opts}=setup();raw.home.injuries=[{name:'Made Up',status:'out',sources:['s']}];expect(validateCollegeContext(raw,opts).sides.home.availability).toBe('partial');raw.home.injuries=[];raw.home.availability='unavailable';expect(validateCollegeContext(raw,opts)).toMatchObject({unavailable:true,sides:{home:{availability:'unavailable'}}});expect(validateCollegeContext(raw,opts).reason).toContain('availability report unavailable');});
 it('preserves sourced unresolved QB reporting as uncertainty instead of inventing a starter',()=>{const{raw,opts}=setup();raw.home.quarterback={name:null,status:'unresolved',note:'Coach has not decided.',sources:['s']};const result=validateCollegeContext(raw,opts);expect(result.unavailable).toBe(true);expect(result.sides.home.quarterback).toBeNull();expect(result.reason).toContain('could not be verified');});
 it('retains valid injuries without a four-player cutoff and uses roster position',()=>{const{raw,opts}=setup();for(let i=0;i<6;i++){opts.rosters.home.push(player(30+i,`Player ${String.fromCharCode(65+i)}`,'OL'));raw.home.injuries.push({name:`Player ${String.fromCharCode(65+i)}`,status:'out for season',sources:['s']});}expect(validateCollegeContext(raw,opts).sides.home.injuries).toHaveLength(6);});
 it('does not accept assistant-generated URLs as search evidence',()=>{const{raw,opts}=setup();opts.sourceRecord=JSON.stringify({type:'item.completed',item:{type:'agent_message',text:JSON.stringify(raw)}});expect(searchSourceTrace(opts.sourceRecord)).toBe('[]');expect(validateCollegeContext(raw,opts).unavailable).toBe(true);});
});
