#!/bin/sh

# ─────────────────────────────────────────────────────────────────────────────
# Xcode Cloud post-clone hook.
#
# Runs after Xcode Cloud clones the repo, BEFORE the build starts. The build
# needs `SecretsLocal.swift` to compile, but that file is gitignored so real
# API keys never leave the local machine. This script writes the file from
# Xcode Cloud's secret environment variables.
#
# REQUIRED Xcode Cloud environment variables (set in App Store Connect →
# Xcode Cloud → your workflow → Environment → Environment Variables):
#
#   XAI_API_KEY        Secret. Your xAI Grok API key (xai-...). Mark as Secret.
#
# Docs: https://developer.apple.com/documentation/xcode/writing-custom-build-scripts
# ─────────────────────────────────────────────────────────────────────────────

set -e  # exit on any error
set -u  # error on unset vars (catches missing env var early)

echo "▶ ci_post_clone.sh: materializing SecretsLocal.swift from CI environment"

# Sanity check — fail loudly if the secret isn't configured
if [ -z "${XAI_API_KEY:-}" ]; then
  echo "❌ XAI_API_KEY environment variable is not set in Xcode Cloud."
  echo "   Add it under App Store Connect → Xcode Cloud → Workflow → Environment →"
  echo "   Environment Variables (mark as Secret)."
  exit 1
fi

# CI_PRIMARY_REPOSITORY_PATH is the absolute path to the cloned repo root
# that Xcode Cloud sets. Fall back to two-up from the script if running locally.
REPO_ROOT="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/../.." && pwd)}"
TARGET_FILE="$REPO_ROOT/ios/GaryApp/SecretsLocal.swift"

echo "▶ Writing $TARGET_FILE"

cat > "$TARGET_FILE" <<EOF
import Foundation

// MARK: - SecretsLocal (generated by Xcode Cloud ci_post_clone.sh)
//
// This file is gitignored — it's regenerated on each CI build from the
// XAI_API_KEY environment variable in Xcode Cloud.

enum SecretsLocal {
    /// xAI Grok API key — used for TTS playback in GaryVoiceService.
    static let xaiAPIKey: String = "${XAI_API_KEY}"
}
EOF

echo "✅ SecretsLocal.swift written ($(wc -c < "$TARGET_FILE") bytes)"

# ─────────────────────────────────────────────────────────────────────────────
# Pre-resolve Swift Package dependencies. Xcode Cloud occasionally fails on
# fresh checkouts with "Missing package product 'FirebaseMessaging'" because
# the SPM graph hasn't been resolved before xcodebuild starts. Running this
# explicitly here makes that race-free.
# ─────────────────────────────────────────────────────────────────────────────
PROJECT_PATH="$REPO_ROOT/ios/GaryApp/GaryApp.xcodeproj"
if [ -d "$PROJECT_PATH" ]; then
  echo "▶ Resolving Swift Package dependencies"
  xcodebuild -resolvePackageDependencies -project "$PROJECT_PATH" 2>&1 | tail -20 || \
    echo "⚠️  resolvePackageDependencies failed — build will retry"
  echo "✅ Package resolution step complete"
else
  echo "⚠️  $PROJECT_PATH not found — skipping package resolution"
fi
