import Foundation

// NCAAFTeams.swift — GENERATED, do not edit by hand.
//
// The college name table: the school without its mascot, and the scoreboard
// abbreviation, both straight from Ball Don't Lie (`college` and
// `abbreviation`). Founder, Sep 4 2026: the game strip read "SAN JOSÉ STATE
// SPARTANS @ EASTERN MICHIGAN EAGLE…" and truncated — "we can just say the
// school name no mascot and use standard ESPN abbreviations where applicable".
//
// Regenerate: node gary2.0/scripts/gen/ncaaf-team-names.js
// Verify in CI/tests: node gary2.0/scripts/gen/ncaaf-team-names.js --check
//
// 1010 keys, 536 teams from the provider.

enum NCAAFTeams {
    /// normalized name (accents and punctuation stripped, lowercased) →
    /// the school and its abbreviation.
    static let byName: [String: (school: String, abbr: String)] = [
    "abilene christian": (school: "Abilene Christian", abbr: "ACU"),
    "abilene christian wildcats": (school: "Abilene Christian", abbr: "ACU"),
    "adams state": (school: "Adams State", abbr: "ADST"),
    "adams state grizzlies": (school: "Adams State", abbr: "ADST"),
    "adrian": (school: "Adrian", abbr: "ADR"),
    "adrian bulldogs": (school: "Adrian", abbr: "ADR"),
    "air force": (school: "Air Force", abbr: "AF"),
    "air force falcons": (school: "Air Force", abbr: "AF"),
    "akron": (school: "Akron", abbr: "AKR"),
    "akron zips": (school: "Akron", abbr: "AKR"),
    "alabama": (school: "Alabama", abbr: "ALA"),
    "alabama a&m": (school: "Alabama A&M", abbr: "AAMU"),
    "alabama a&m bulldogs": (school: "Alabama A&M", abbr: "AAMU"),
    "alabama crimson tide": (school: "Alabama", abbr: "ALA"),
    "alabama state": (school: "Alabama State", abbr: "ALST"),
    "alabama state hornets": (school: "Alabama State", abbr: "ALST"),
    "albany state (ga)": (school: "Albany State (GA)", abbr: "ALB"),
    "albany state (ga) golden rams": (school: "Albany State (GA)", abbr: "ALB"),
    "albion": (school: "Albion", abbr: "ALBI"),
    "albion britons": (school: "Albion", abbr: "ALBI"),
    "alcorn state": (school: "Alcorn State", abbr: "ALCN"),
    "alcorn state braves": (school: "Alcorn State", abbr: "ALCN"),
    "aldersonbroaddus": (school: "Alderson-Broaddus", abbr: "ABC"),
    "aldersonbroaddus battlers": (school: "Alderson-Broaddus", abbr: "ABC"),
    "allen": (school: "Allen", abbr: "ALN"),
    "allen yellow jackets": (school: "Allen", abbr: "ALN"),
    "american international": (school: "American International", abbr: "AIC"),
    "american international yellow jackets": (school: "American International", abbr: "AIC"),
    "anderson (sc)": (school: "Anderson (SC)", abbr: "AND"),
    "anderson (sc) trojans": (school: "Anderson (SC)", abbr: "AND"),
    "angelo state": (school: "Angelo State", abbr: "ANG"),
    "angelo state rams": (school: "Angelo State", abbr: "ANG"),
    "app state": (school: "App State", abbr: "APP"),
    "app state mountaineers": (school: "App State", abbr: "APP"),
    "apprentice school": (school: "Apprentice School", abbr: "APP"),
    "apprentice school builders": (school: "Apprentice School", abbr: "APP"),
    "arizona": (school: "Arizona", abbr: "ARIZ"),
    "arizona christian": (school: "Arizona Christian", abbr: "ARI"),
    "arizona christian firestorm": (school: "Arizona Christian", abbr: "ARI"),
    "arizona state": (school: "Arizona State", abbr: "ASU"),
    "arizona state sun devils": (school: "Arizona State", abbr: "ASU"),
    "arizona wildcats": (school: "Arizona", abbr: "ARIZ"),
    "arkansas": (school: "Arkansas", abbr: "ARK"),
    "arkansas baptist": (school: "Arkansas Baptist", abbr: "ARKAN"),
    "arkansas baptist buffaloes": (school: "Arkansas Baptist", abbr: "ARKAN"),
    "arkansas razorbacks": (school: "Arkansas", abbr: "ARK"),
    "arkansas state": (school: "Arkansas State", abbr: "ARST"),
    "arkansas state red wolves": (school: "Arkansas State", abbr: "ARST"),
    "arkansas tech": (school: "Arkansas Tech", abbr: "ARK"),
    "arkansas tech wonder boys": (school: "Arkansas Tech", abbr: "ARK"),
    "arkansasmonticello": (school: "Arkansas-Monticello", abbr: "ARK"),
    "arkansasmonticello weevils": (school: "Arkansas-Monticello", abbr: "ARK"),
    "arkansaspine bluff": (school: "Arkansas-Pine Bluff", abbr: "UAPB"),
    "arkansaspine bluff golden lions": (school: "Arkansas-Pine Bluff", abbr: "UAPB"),
    "army": (school: "Army", abbr: "ARMY"),
    "army black knights": (school: "Army", abbr: "ARMY"),
    "auburn": (school: "Auburn", abbr: "AUB"),
    "auburn tigers": (school: "Auburn", abbr: "AUB"),
    "augustana (sd)": (school: "Augustana (SD)", abbr: "AUG"),
    "augustana (sd) vikings": (school: "Augustana (SD)", abbr: "AUG"),
    "aurora": (school: "Aurora", abbr: "AUR"),
    "aurora spartans": (school: "Aurora", abbr: "AUR"),
    "austin peay": (school: "Austin Peay", abbr: "APSU"),
    "austin peay governors": (school: "Austin Peay", abbr: "APSU"),
    "azusa pacific": (school: "Azusa Pacific", abbr: "AZU"),
    "azusa pacific cougars": (school: "Azusa Pacific", abbr: "AZU"),
    "bacone": (school: "Bacone", abbr: "BACONE"),
    "ball state": (school: "Ball State", abbr: "BALL"),
    "ball state cardinals": (school: "Ball State", abbr: "BALL"),
    "barton college": (school: "Barton College", abbr: "BAR"),
    "barton college bulldogs": (school: "Barton College", abbr: "BAR"),
    "baylor": (school: "Baylor", abbr: "BAY"),
    "baylor bears": (school: "Baylor", abbr: "BAY"),
    "benedict college": (school: "Benedict College", abbr: "BEN"),
    "benedict college tigers": (school: "Benedict College", abbr: "BEN"),
    "bentley": (school: "Bentley", abbr: "BEN"),
    "bentley falcons": (school: "Bentley", abbr: "BEN"),
    "berry college": (school: "Berry College", abbr: "BER"),
    "berry college vikings": (school: "Berry College", abbr: "BER"),
    "bethany (ks)": (school: "Bethany (KS)", abbr: "BET"),
    "bethany (ks) swedes": (school: "Bethany (KS)", abbr: "BET"),
    "bethel (tn)": (school: "Bethel (TN)", abbr: "BET"),
    "bethel (tn) wildcats": (school: "Bethel (TN)", abbr: "BET"),
    "bethunecookman": (school: "Bethune-Cookman", abbr: "BCU"),
    "bethunecookman wildcats": (school: "Bethune-Cookman", abbr: "BCU"),
    "birminghamsouthern": (school: "Birmingham-Southern", abbr: "BIR"),
    "birminghamsouthern panthers": (school: "Birmingham-Southern", abbr: "BIR"),
    "black hills state": (school: "Black Hills State", abbr: "BLA"),
    "black hills state yellow jackets": (school: "Black Hills State", abbr: "BLA"),
    "bloomsburg": (school: "Bloomsburg", abbr: "BLOM"),
    "bloomsburg huskies": (school: "Bloomsburg", abbr: "BLOM"),
    "bluefield college": (school: "Bluefield College", abbr: "BLU"),
    "bluefield college rams": (school: "Bluefield College", abbr: "BLU"),
    "boise state": (school: "Boise State", abbr: "BOIS"),
    "boise state broncos": (school: "Boise State", abbr: "BOIS"),
    "boston college": (school: "Boston College", abbr: "BC"),
    "boston college eagles": (school: "Boston College", abbr: "BC"),
    "bowling green": (school: "Bowling Green", abbr: "BGSU"),
    "bowling green falcons": (school: "Bowling Green", abbr: "BGSU"),
    "brevard college": (school: "Brevard College", abbr: "BRE"),
    "brevard college tornados": (school: "Brevard College", abbr: "BRE"),
    "brown": (school: "Brown", abbr: "BRWN"),
    "brown bears": (school: "Brown", abbr: "BRWN"),
    "bryant": (school: "Bryant", abbr: "BRY"),
    "bryant bulldogs": (school: "Bryant", abbr: "BRY"),
    "bucknell": (school: "Bucknell", abbr: "BUCK"),
    "bucknell bison": (school: "Bucknell", abbr: "BUCK"),
    "buffalo": (school: "Buffalo", abbr: "BUF"),
    "buffalo bulls": (school: "Buffalo", abbr: "BUF"),
    "buffalo state": (school: "Buffalo State", abbr: "BUF"),
    "buffalo state bengals": (school: "Buffalo State", abbr: "BUF"),
    "butler": (school: "Butler", abbr: "BUT"),
    "butler bulldogs": (school: "Butler", abbr: "BUT"),
    "byu": (school: "BYU", abbr: "BYU"),
    "byu cougars": (school: "BYU", abbr: "BYU"),
    "cal poly": (school: "Cal Poly", abbr: "CP"),
    "cal poly mustangs": (school: "Cal Poly", abbr: "CP"),
    "california": (school: "California", abbr: "CAL"),
    "california golden bears": (school: "California", abbr: "CAL"),
    "campbell": (school: "Campbell", abbr: "CAM"),
    "campbell fighting camels": (school: "Campbell", abbr: "CAM"),
    "campbellsville": (school: "Campbellsville", abbr: "CAI"),
    "campbellsville tigers": (school: "Campbellsville", abbr: "CAI"),
    "carnegie mellon": (school: "Carnegie Mellon", abbr: "CAR"),
    "carnegie mellon tartans": (school: "Carnegie Mellon", abbr: "CAR"),
    "carroll college (mt)": (school: "Carroll College (MT)", abbr: "CARROLLMT"),
    "carroll college (mt) fighting saints": (school: "Carroll College (MT)", abbr: "CARROLLMT"),
    "carsonnewman": (school: "Carson-Newman", abbr: "CNEW"),
    "carsonnewman eagles": (school: "Carson-Newman", abbr: "CNEW"),
    "carthage": (school: "Carthage", abbr: "CAR"),
    "carthage redmen": (school: "Carthage", abbr: "CAR"),
    "catawba": (school: "Catawba", abbr: "CAT"),
    "catawba indians": (school: "Catawba", abbr: "CAT"),
    "catholic university": (school: "Catholic University", abbr: "CAT"),
    "catholic university cardinals": (school: "Catholic University", abbr: "CAT"),
    "central arkansas": (school: "Central Arkansas", abbr: "CARK"),
    "central arkansas bears": (school: "Central Arkansas", abbr: "CARK"),
    "central connecticut": (school: "Central Connecticut", abbr: "CCSU"),
    "central connecticut blue devils": (school: "Central Connecticut", abbr: "CCSU"),
    "central methodist": (school: "Central Methodist", abbr: "CDF"),
    "central methodist eagles": (school: "Central Methodist", abbr: "CDF"),
    "central michigan": (school: "Central Michigan", abbr: "CMU"),
    "central michigan chippewas": (school: "Central Michigan", abbr: "CMU"),
    "central missouri state": (school: "Central Missouri State", abbr: "CEN"),
    "central missouri state mules": (school: "Central Missouri State", abbr: "CEN"),
    "central oklahoma": (school: "Central Oklahoma", abbr: "CENO"),
    "central oklahoma bronchos": (school: "Central Oklahoma", abbr: "CENO"),
    "central washington": (school: "Central Washington", abbr: "CEN"),
    "central washington wildcats": (school: "Central Washington", abbr: "CEN"),
    "chadron state": (school: "Chadron State", abbr: "CHA"),
    "chadron state eagles": (school: "Chadron State", abbr: "CHA"),
    "chapman": (school: "Chapman", abbr: "CHA"),
    "chapman panthers": (school: "Chapman", abbr: "CHA"),
    "charleston (wv)": (school: "Charleston (WV)", abbr: "CHA"),
    "charleston (wv) golden eagles": (school: "Charleston (WV)", abbr: "CHA"),
    "charleston southern": (school: "Charleston Southern", abbr: "CHSO"),
    "charleston southern buccaneers": (school: "Charleston Southern", abbr: "CHSO"),
    "charlotte": (school: "Charlotte", abbr: "CLT"),
    "charlotte 49ers": (school: "Charlotte", abbr: "CLT"),
    "chattanooga": (school: "Chattanooga", abbr: "UTC"),
    "chattanooga mocs": (school: "Chattanooga", abbr: "UTC"),
    "cheyney": (school: "Cheyney", abbr: "CHE"),
    "cheyney wolves": (school: "Cheyney", abbr: "CHE"),
    "chicago state": (school: "Chicago State", abbr: "CHI"),
    "chicago state cougars": (school: "Chicago State", abbr: "CHI"),
    "cincinnati": (school: "Cincinnati", abbr: "CIN"),
    "cincinnati bearcats": (school: "Cincinnati", abbr: "CIN"),
    "clarion": (school: "Clarion", abbr: "CLA"),
    "clarion golden eagles": (school: "Clarion", abbr: "CLA"),
    "clark atlanta": (school: "Clark Atlanta", abbr: "CLK"),
    "clark atlanta panthers": (school: "Clark Atlanta", abbr: "CLK"),
    "clemson": (school: "Clemson", abbr: "CLEM"),
    "clemson tigers": (school: "Clemson", abbr: "CLEM"),
    "coastal carolina": (school: "Coastal Carolina", abbr: "CCU"),
    "coastal carolina chanticleers": (school: "Coastal Carolina", abbr: "CCU"),
    "colgate": (school: "Colgate", abbr: "COLG"),
    "colgate raiders": (school: "Colgate", abbr: "COLG"),
    "college of faith": (school: "College of Faith", abbr: "FAI"),
    "college of faith charlotte": (school: "College of Faith - Charlotte", abbr: "COFC"),
    "college of faith charlotte saints": (school: "College of Faith - Charlotte", abbr: "COFC"),
    "college of faith warriors": (school: "College of Faith", abbr: "FAI"),
    "college of idaho": (school: "College of Idaho", abbr: "COI"),
    "college of idaho yotes": (school: "College of Idaho", abbr: "COI"),
    "colorado": (school: "Colorado", abbr: "COLO"),
    "colorado buffaloes": (school: "Colorado", abbr: "COLO"),
    "colorado mesa": (school: "Colorado Mesa", abbr: "MESA"),
    "colorado mesa mavericks": (school: "Colorado Mesa", abbr: "MESA"),
    "colorado state": (school: "Colorado State", abbr: "CSU"),
    "colorado state rams": (school: "Colorado State", abbr: "CSU"),
    "columbia": (school: "Columbia", abbr: "COLU"),
    "columbia lions": (school: "Columbia", abbr: "COLU"),
    "concord": (school: "Concord", abbr: "CON"),
    "concord mountain lions": (school: "Concord", abbr: "CON"),
    "concordia (al)": (school: "Concordia (AL)", abbr: "CON"),
    "concordia (al) hornets": (school: "Concordia (AL)", abbr: "CON"),
    "concordia (wi)": (school: "Concordia (WI)", abbr: "CON"),
    "concordia (wi) falcons": (school: "Concordia (WI)", abbr: "CON"),
    "concordia college (mi)": (school: "Concordia College (MI)", abbr: "CMI"),
    "concordia college (mi) cardinals": (school: "Concordia College (MI)", abbr: "CMI"),
    "cornell": (school: "Cornell", abbr: "COR"),
    "cornell big red": (school: "Cornell", abbr: "COR"),
    "cumberland (tn)": (school: "Cumberland (TN)", abbr: "CUMBTN"),
    "cumberland (tn) bulldogs": (school: "Cumberland (TN)", abbr: "CUMBTN"),
    "cumberland college": (school: "Cumberland College", abbr: "CUM"),
    "cumberland college indians": (school: "Cumberland College", abbr: "CUM"),
    "dartmouth": (school: "Dartmouth", abbr: "DART"),
    "dartmouth big green": (school: "Dartmouth", abbr: "DART"),
    "davidson": (school: "Davidson", abbr: "DAV"),
    "davidson wildcats": (school: "Davidson", abbr: "DAV"),
    "dayton": (school: "Dayton", abbr: "DAY"),
    "dayton flyers": (school: "Dayton", abbr: "DAY"),
    "delaware": (school: "Delaware", abbr: "DEL"),
    "delaware blue hens": (school: "Delaware", abbr: "DEL"),
    "delaware state": (school: "Delaware State", abbr: "DSU"),
    "delaware state hornets": (school: "Delaware State", abbr: "DSU"),
    "delaware valley": (school: "Delaware Valley", abbr: "DV"),
    "delaware valley aggies": (school: "Delaware Valley", abbr: "DV"),
    "delta state": (school: "Delta State", abbr: "DELTAST"),
    "delta state statesmen": (school: "Delta State", abbr: "DELTAST"),
    "depauw": (school: "DePauw", abbr: "DEP"),
    "depauw tigers": (school: "DePauw", abbr: "DEP"),
    "dickinson (pa)": (school: "Dickinson (PA)", abbr: "DCK"),
    "dickinson (pa) red devils": (school: "Dickinson (PA)", abbr: "DCK"),
    "drake": (school: "Drake", abbr: "DRKE"),
    "drake bulldogs": (school: "Drake", abbr: "DRKE"),
    "duke": (school: "Duke", abbr: "DUKE"),
    "duke blue devils": (school: "Duke", abbr: "DUKE"),
    "duquesne": (school: "Duquesne", abbr: "DUQ"),
    "duquesne dukes": (school: "Duquesne", abbr: "DUQ"),
    "east carolina": (school: "East Carolina", abbr: "ECU"),
    "east carolina pirates": (school: "East Carolina", abbr: "ECU"),
    "east central": (school: "East Central", abbr: "EAS"),
    "east central tigers": (school: "East Central", abbr: "EAS"),
    "east stroudsburg": (school: "East Stroudsburg", abbr: "EAS"),
    "east stroudsburg warriors": (school: "East Stroudsburg", abbr: "EAS"),
    "east tennessee state": (school: "East Tennessee State", abbr: "ETSU"),
    "east tennessee state buccaneers": (school: "East Tennessee State", abbr: "ETSU"),
    "east texas a&m": (school: "East Texas A&M", abbr: "ETAM"),
    "east texas a&m lions": (school: "East Texas A&M", abbr: "ETAM"),
    "eastern illinois": (school: "Eastern Illinois", abbr: "EIU"),
    "eastern illinois panthers": (school: "Eastern Illinois", abbr: "EIU"),
    "eastern kentucky": (school: "Eastern Kentucky", abbr: "EKU"),
    "eastern kentucky colonels": (school: "Eastern Kentucky", abbr: "EKU"),
    "eastern michigan": (school: "Eastern Michigan", abbr: "EMU"),
    "eastern michigan eagles": (school: "Eastern Michigan", abbr: "EMU"),
    "eastern new mexico": (school: "Eastern New Mexico", abbr: "EAS"),
    "eastern new mexico greyhounds": (school: "Eastern New Mexico", abbr: "EAS"),
    "eastern oregon": (school: "Eastern Oregon", abbr: "EAS"),
    "eastern oregon mountaineers": (school: "Eastern Oregon", abbr: "EAS"),
    "eastern washington": (school: "Eastern Washington", abbr: "EWU"),
    "eastern washington eagles": (school: "Eastern Washington", abbr: "EWU"),
    "edinboro": (school: "Edinboro", abbr: "EDI"),
    "edinboro fighting scots": (school: "Edinboro", abbr: "EDI"),
    "elizabeth city state": (school: "Elizabeth City State", abbr: "ELI"),
    "elizabeth city state vikings": (school: "Elizabeth City State", abbr: "ELI"),
    "elon": (school: "Elon", abbr: "ELON"),
    "elon phoenix": (school: "Elon", abbr: "ELON"),
    "erskine": (school: "Erskine", abbr: "ERS"),
    "erskine flying fleet": (school: "Erskine", abbr: "ERS"),
    "evangel": (school: "Evangel", abbr: "EVA"),
    "evangel crusaders": (school: "Evangel", abbr: "EVA"),
    "fairmont state": (school: "Fairmont State", abbr: "FAI"),
    "fairmont state falcons": (school: "Fairmont State", abbr: "FAI"),
    "faulkner": (school: "Faulkner", abbr: "FAU"),
    "faulkner eagles": (school: "Faulkner", abbr: "FAU"),
    "fayetteville state": (school: "Fayetteville State", abbr: "FAY"),
    "fayetteville state broncos": (school: "Fayetteville State", abbr: "FAY"),
    "ferris state": (school: "Ferris State", abbr: "FER"),
    "ferris state bulldogs": (school: "Ferris State", abbr: "FER"),
    "ferrum": (school: "Ferrum", abbr: "FER"),
    "ferrum panthers": (school: "Ferrum", abbr: "FER"),
    "florida": (school: "Florida", abbr: "FLA"),
    "florida a&m": (school: "Florida A&M", abbr: "FAMU"),
    "florida a&m rattlers": (school: "Florida A&M", abbr: "FAMU"),
    "florida atlantic": (school: "Florida Atlantic", abbr: "FAU"),
    "florida atlantic owls": (school: "Florida Atlantic", abbr: "FAU"),
    "florida gators": (school: "Florida", abbr: "FLA"),
    "florida international": (school: "Florida International", abbr: "FIU"),
    "florida international panthers": (school: "Florida International", abbr: "FIU"),
    "florida memorial university": (school: "Florida Memorial University", abbr: "FLMRL"),
    "florida memorial university lions": (school: "Florida Memorial University", abbr: "FLMRL"),
    "florida state": (school: "Florida State", abbr: "FSU"),
    "florida state seminoles": (school: "Florida State", abbr: "FSU"),
    "florida tech": (school: "Florida Tech", abbr: "FLTH"),
    "florida tech panthers": (school: "Florida Tech", abbr: "FLTH"),
    "fordham": (school: "Fordham", abbr: "FOR"),
    "fordham rams": (school: "Fordham", abbr: "FOR"),
    "fort lewis": (school: "Fort Lewis", abbr: "FORTLEW"),
    "fort lewis skyhawks": (school: "Fort Lewis", abbr: "FORTLEW"),
    "fort valley state": (school: "Fort Valley State", abbr: "FOR"),
    "fort valley state wildcats": (school: "Fort Valley State", abbr: "FOR"),
    "franklin": (school: "Franklin", abbr: "FRA"),
    "franklin grizzlies": (school: "Franklin", abbr: "FRA"),
    "franklin pierce": (school: "Franklin Pierce", abbr: "FP"),
    "franklin pierce ravens": (school: "Franklin Pierce", abbr: "FP"),
    "fresno state": (school: "Fresno State", abbr: "FRES"),
    "fresno state bulldogs": (school: "Fresno State", abbr: "FRES"),
    "frostburg state": (school: "Frostburg State", abbr: "FRO"),
    "frostburg state bobcats": (school: "Frostburg State", abbr: "FRO"),
    "furman": (school: "Furman", abbr: "FUR"),
    "furman paladins": (school: "Furman", abbr: "FUR"),
    "gardnerwebb": (school: "Gardner-Webb", abbr: "GWEB"),
    "gardnerwebb runnin bulldogs": (school: "Gardner-Webb", abbr: "GWEB"),
    "georgetown": (school: "Georgetown", abbr: "GTWN"),
    "georgetown college kentucky": (school: "Georgetown College Kentucky", abbr: "GTOWNCOLL"),
    "georgetown college kentucky tigers": (school: "Georgetown College Kentucky", abbr: "GTOWNCOLL"),
    "georgetown hoyas": (school: "Georgetown", abbr: "GTWN"),
    "georgia": (school: "Georgia", abbr: "UGA"),
    "georgia bulldogs": (school: "Georgia", abbr: "UGA"),
    "georgia southern": (school: "Georgia Southern", abbr: "GASO"),
    "georgia southern eagles": (school: "Georgia Southern", abbr: "GASO"),
    "georgia state": (school: "Georgia State", abbr: "GAST"),
    "georgia state panthers": (school: "Georgia State", abbr: "GAST"),
    "georgia tech": (school: "Georgia Tech", abbr: "GT"),
    "georgia tech yellow jackets": (school: "Georgia Tech", abbr: "GT"),
    "glenville state": (school: "Glenville State", abbr: "GLE"),
    "glenville state pioneers": (school: "Glenville State", abbr: "GLE"),
    "grambling": (school: "Grambling", abbr: "GRAM"),
    "grambling tigers": (school: "Grambling", abbr: "GRAM"),
    "grand view": (school: "Grand View", abbr: "GV"),
    "grand view vikings": (school: "Grand View", abbr: "GV"),
    "greensboro college": (school: "Greensboro College", abbr: "GRNSBORO"),
    "greensboro college pride": (school: "Greensboro College", abbr: "GRNSBORO"),
    "guilford": (school: "Guilford", abbr: "GUI"),
    "guilford quakers": (school: "Guilford", abbr: "GUI"),
    "hampton": (school: "Hampton", abbr: "HAMP"),
    "hampton pirates": (school: "Hampton", abbr: "HAMP"),
    "hanover": (school: "Hanover", abbr: "HAN"),
    "hanover panthers": (school: "Hanover", abbr: "HAN"),
    "harvard": (school: "Harvard", abbr: "HARV"),
    "harvard crimson": (school: "Harvard", abbr: "HARV"),
    "hawaii": (school: "Hawai'i", abbr: "HAW"),
    "hawaii rainbow warriors": (school: "Hawai'i", abbr: "HAW"),
    "henderson state": (school: "Henderson State", abbr: "HEN"),
    "henderson state reddies": (school: "Henderson State", abbr: "HEN"),
    "holy cross": (school: "Holy Cross", abbr: "HC"),
    "holy cross crusaders": (school: "Holy Cross", abbr: "HC"),
    "houston": (school: "Houston", abbr: "HOU"),
    "houston christian": (school: "Houston Christian", abbr: "HCU"),
    "houston christian huskies": (school: "Houston Christian", abbr: "HCU"),
    "houston cougars": (school: "Houston", abbr: "HOU"),
    "howard": (school: "Howard", abbr: "HOW"),
    "howard bison": (school: "Howard", abbr: "HOW"),
    "humboldt state": (school: "Humboldt State", abbr: "HUM"),
    "humboldt state lumberjacks": (school: "Humboldt State", abbr: "HUM"),
    "idaho": (school: "Idaho", abbr: "IDHO"),
    "idaho state": (school: "Idaho State", abbr: "IDST"),
    "idaho state bengals": (school: "Idaho State", abbr: "IDST"),
    "idaho vandals": (school: "Idaho", abbr: "IDHO"),
    "illinois": (school: "Illinois", abbr: "ILL"),
    "illinois fighting illini": (school: "Illinois", abbr: "ILL"),
    "illinois state": (school: "Illinois State", abbr: "ILST"),
    "illinois state redbirds": (school: "Illinois State", abbr: "ILST"),
    "incarnate word": (school: "Incarnate Word", abbr: "UIW"),
    "incarnate word cardinals": (school: "Incarnate Word", abbr: "UIW"),
    "indiana": (school: "Indiana", abbr: "IU"),
    "indiana hoosiers": (school: "Indiana", abbr: "IU"),
    "indiana state": (school: "Indiana State", abbr: "INST"),
    "indiana state sycamores": (school: "Indiana State", abbr: "INST"),
    "indianapolis": (school: "Indianapolis", abbr: "IND"),
    "indianapolis greyhounds": (school: "Indianapolis", abbr: "IND"),
    "iona": (school: "Iona", abbr: "IONA"),
    "iona gaels": (school: "Iona", abbr: "IONA"),
    "iowa": (school: "Iowa", abbr: "IOWA"),
    "iowa hawkeyes": (school: "Iowa", abbr: "IOWA"),
    "iowa state": (school: "Iowa State", abbr: "ISU"),
    "iowa state cyclones": (school: "Iowa State", abbr: "ISU"),
    "iowa wesleyan": (school: "Iowa Wesleyan", abbr: "IOW"),
    "iowa wesleyan tigers": (school: "Iowa Wesleyan", abbr: "IOW"),
    "jackson state": (school: "Jackson State", abbr: "JKST"),
    "jackson state tigers": (school: "Jackson State", abbr: "JKST"),
    "jacksonville state": (school: "Jacksonville State", abbr: "JXST"),
    "jacksonville state gamecocks": (school: "Jacksonville State", abbr: "JXST"),
    "james madison": (school: "James Madison", abbr: "JMU"),
    "james madison dukes": (school: "James Madison", abbr: "JMU"),
    "johnson c smith": (school: "Johnson C Smith", abbr: "JOH"),
    "johnson c smith golden bulls": (school: "Johnson C Smith", abbr: "JOH"),
    "kalamazoo": (school: "Kalamazoo", abbr: "KAL"),
    "kalamazoo hornets": (school: "Kalamazoo", abbr: "KAL"),
    "kansas": (school: "Kansas", abbr: "KU"),
    "kansas jayhawks": (school: "Kansas", abbr: "KU"),
    "kansas state": (school: "Kansas State", abbr: "KSU"),
    "kansas state wildcats": (school: "Kansas State", abbr: "KSU"),
    "kennesaw state": (school: "Kennesaw State", abbr: "KENN"),
    "kennesaw state owls": (school: "Kennesaw State", abbr: "KENN"),
    "kent state": (school: "Kent State", abbr: "KENT"),
    "kent state golden flashes": (school: "Kent State", abbr: "KENT"),
    "kentucky": (school: "Kentucky", abbr: "UK"),
    "kentucky christian": (school: "Kentucky Christian", abbr: "KCU"),
    "kentucky christian knights": (school: "Kentucky Christian", abbr: "KCU"),
    "kentucky state": (school: "Kentucky State", abbr: "KYS"),
    "kentucky state thorobreds": (school: "Kentucky State", abbr: "KYS"),
    "kentucky wesleyan": (school: "Kentucky Wesleyan", abbr: "KYW"),
    "kentucky wesleyan panthers": (school: "Kentucky Wesleyan", abbr: "KYW"),
    "kentucky wildcats": (school: "Kentucky", abbr: "UK"),
    "la salle": (school: "La Salle", abbr: "LAS"),
    "la salle explorers": (school: "La Salle", abbr: "LAS"),
    "la verne": (school: "La Verne", abbr: "LA"),
    "la verne leopards": (school: "La Verne", abbr: "LA"),
    "lafayette": (school: "Lafayette", abbr: "LAF"),
    "lafayette leopards": (school: "Lafayette", abbr: "LAF"),
    "lamar": (school: "Lamar", abbr: "LAM"),
    "lamar cardinals": (school: "Lamar", abbr: "LAM"),
    "lambuth": (school: "Lambuth", abbr: "LAM"),
    "lambuth eagles": (school: "Lambuth", abbr: "LAM"),
    "lane": (school: "Lane", abbr: "LAN"),
    "lane dragons": (school: "Lane", abbr: "LAN"),
    "langston university": (school: "Langston University", abbr: "LANGSTON"),
    "langston university lions": (school: "Langston University", abbr: "LANGSTON"),
    "lawrence tech": (school: "Lawrence Tech", abbr: "LTC"),
    "lawrence tech lawte": (school: "Lawrence Tech", abbr: "LTC"),
    "lehigh": (school: "Lehigh", abbr: "LEH"),
    "lehigh mountain hawks": (school: "Lehigh", abbr: "LEH"),
    "lenoirrhyne": (school: "Lenoir-Rhyne", abbr: "LEN"),
    "lenoirrhyne bears": (school: "Lenoir-Rhyne", abbr: "LEN"),
    "liberty": (school: "Liberty", abbr: "LIB"),
    "liberty flames": (school: "Liberty", abbr: "LIB"),
    "limestone": (school: "Limestone", abbr: "LIM"),
    "limestone saints": (school: "Limestone", abbr: "LIM"),
    "lincoln (mo)": (school: "Lincoln (MO)", abbr: "LIN"),
    "lincoln (mo) blue tigers": (school: "Lincoln (MO)", abbr: "LIN"),
    "lincoln (pa)": (school: "Lincoln (PA)", abbr: "LIN"),
    "lincoln (pa) lions": (school: "Lincoln (PA)", abbr: "LIN"),
    "lincoln university (ca)": (school: "Lincoln University (CA)", abbr: "LIN"),
    "lincoln university (ca) oaklanders": (school: "Lincoln University (CA)", abbr: "LIN"),
    "lindenwood": (school: "Lindenwood", abbr: "LIN"),
    "lindenwood lions": (school: "Lindenwood", abbr: "LIN"),
    "livingstone": (school: "Livingstone", abbr: "LVI"),
    "livingstone blue bears": (school: "Livingstone", abbr: "LVI"),
    "lock haven": (school: "Lock Haven", abbr: "LOC"),
    "lock haven bald eagles": (school: "Lock Haven", abbr: "LOC"),
    "long island university": (school: "Long Island University", abbr: "LIU"),
    "long island university sharks": (school: "Long Island University", abbr: "LIU"),
    "louisiana": (school: "Louisiana", abbr: "UL"),
    "louisiana college": (school: "Louisiana College", abbr: "LAC"),
    "louisiana college wildcats": (school: "Louisiana College", abbr: "LAC"),
    "louisiana ragin cajuns": (school: "Louisiana", abbr: "UL"),
    "louisiana tech": (school: "Louisiana Tech", abbr: "LT"),
    "louisiana tech bulldogs": (school: "Louisiana Tech", abbr: "LT"),
    "louisville": (school: "Louisville", abbr: "LOU"),
    "louisville cardinals": (school: "Louisville", abbr: "LOU"),
    "lsu": (school: "LSU", abbr: "LSU"),
    "lsu tigers": (school: "LSU", abbr: "LSU"),
    "maine": (school: "Maine", abbr: "ME"),
    "maine black bears": (school: "Maine", abbr: "ME"),
    "malone": (school: "Malone", abbr: "MAL"),
    "malone pioneers": (school: "Malone", abbr: "MAL"),
    "marian": (school: "Marian", abbr: "MAR"),
    "marian knights": (school: "Marian", abbr: "MAR"),
    "marist": (school: "Marist", abbr: "MRST"),
    "marist red foxes": (school: "Marist", abbr: "MRST"),
    "mars hill": (school: "Mars Hill", abbr: "MH"),
    "mars hill lions": (school: "Mars Hill", abbr: "MH"),
    "marshall": (school: "Marshall", abbr: "MRSH"),
    "marshall thundering herd": (school: "Marshall", abbr: "MRSH"),
    "maryland": (school: "Maryland", abbr: "MD"),
    "maryland terrapins": (school: "Maryland", abbr: "MD"),
    "maryville tn": (school: "Maryville TN", abbr: "MAR"),
    "maryville tn fighting scots": (school: "Maryville TN", abbr: "MAR"),
    "massachusetts": (school: "Massachusetts", abbr: "MASS"),
    "massachusetts minutemen": (school: "Massachusetts", abbr: "MASS"),
    "mayville state": (school: "Mayville State", abbr: "MAY"),
    "mayville state comets": (school: "Mayville State", abbr: "MAY"),
    "mckendree": (school: "McKendree", abbr: "MAN"),
    "mckendree bearcats": (school: "McKendree", abbr: "MAN"),
    "mcmurry": (school: "McMurry", abbr: "MCM"),
    "mcmurry war hawks": (school: "McMurry", abbr: "MCM"),
    "mcneese": (school: "McNeese", abbr: "MCN"),
    "mcneese cowboys": (school: "McNeese", abbr: "MCN"),
    "memphis": (school: "Memphis", abbr: "MEM"),
    "memphis tigers": (school: "Memphis", abbr: "MEM"),
    "menlo college": (school: "Menlo College", abbr: "MENLO"),
    "menlo college oaks": (school: "Menlo College", abbr: "MENLO"),
    "mercer": (school: "Mercer", abbr: "MER"),
    "mercer bears": (school: "Mercer", abbr: "MER"),
    "mercyhurst": (school: "Mercyhurst", abbr: "MERC"),
    "mercyhurst lakers": (school: "Mercyhurst", abbr: "MERC"),
    "merrimack": (school: "Merrimack", abbr: "MRMK"),
    "merrimack warriors": (school: "Merrimack", abbr: "MRMK"),
    "methodist": (school: "Methodist", abbr: "MTH"),
    "methodist monarchs": (school: "Methodist", abbr: "MTH"),
    "miami": (school: "Miami", abbr: "MIA"),
    "miami (oh)": (school: "Miami (OH)", abbr: "M-OH"),
    "miami (oh) redhawks": (school: "Miami (OH)", abbr: "M-OH"),
    "miami hurricanes": (school: "Miami", abbr: "MIA"),
    "michigan": (school: "Michigan", abbr: "MICH"),
    "michigan state": (school: "Michigan State", abbr: "MSU"),
    "michigan state spartans": (school: "Michigan State", abbr: "MSU"),
    "michigan tech": (school: "Michigan Tech", abbr: "MTU"),
    "michigan tech huskies": (school: "Michigan Tech", abbr: "MTU"),
    "michigan wolverines": (school: "Michigan", abbr: "MICH"),
    "middle tennessee": (school: "Middle Tennessee", abbr: "MTSU"),
    "middle tennessee blue raiders": (school: "Middle Tennessee", abbr: "MTSU"),
    "midwestern state": (school: "Midwestern State", abbr: "MID"),
    "midwestern state mustangs": (school: "Midwestern State", abbr: "MID"),
    "miles": (school: "Miles", abbr: "MIL"),
    "miles golden bears": (school: "Miles", abbr: "MIL"),
    "millersville": (school: "Millersville", abbr: "MIL"),
    "millersville marauders": (school: "Millersville", abbr: "MIL"),
    "minnesota": (school: "Minnesota", abbr: "MINN"),
    "minnesota duluth": (school: "Minnesota Duluth", abbr: "UMD"),
    "minnesota duluth bulldogs": (school: "Minnesota Duluth", abbr: "UMD"),
    "minnesota golden gophers": (school: "Minnesota", abbr: "MINN"),
    "minnesota state": (school: "Minnesota State", abbr: "MNST"),
    "minnesota state mavericks": (school: "Minnesota State", abbr: "MNST"),
    "minot state": (school: "Minot State", abbr: "MIN"),
    "minot state beavers": (school: "Minot State", abbr: "MIN"),
    "mississippi state": (school: "Mississippi State", abbr: "MSST"),
    "mississippi state bulldogs": (school: "Mississippi State", abbr: "MSST"),
    "mississippi valley state": (school: "Mississippi Valley State", abbr: "MVSU"),
    "mississippi valley state delta devils": (school: "Mississippi Valley State", abbr: "MVSU"),
    "missouri": (school: "Missouri", abbr: "MIZ"),
    "missouri baptist": (school: "Missouri Baptist", abbr: "MB"),
    "missouri baptist spartans": (school: "Missouri Baptist", abbr: "MB"),
    "missouri s&t": (school: "Missouri S&T", abbr: "MIS"),
    "missouri s&t miners": (school: "Missouri S&T", abbr: "MIS"),
    "missouri state": (school: "Missouri State", abbr: "MOST"),
    "missouri state bears": (school: "Missouri State", abbr: "MOST"),
    "missouri tigers": (school: "Missouri", abbr: "MIZ"),
    "missouri western": (school: "Missouri Western", abbr: "MIS"),
    "missouri western griffons": (school: "Missouri Western", abbr: "MIS"),
    "monmouth": (school: "Monmouth", abbr: "MONM"),
    "monmouth hawks": (school: "Monmouth", abbr: "MONM"),
    "montana": (school: "Montana", abbr: "MONT"),
    "montana grizzlies": (school: "Montana", abbr: "MONT"),
    "montana state": (school: "Montana State", abbr: "MTST"),
    "montana state bobcats": (school: "Montana State", abbr: "MTST"),
    "montanawestern": (school: "Montana-Western", abbr: "MWST"),
    "montanawestern bulldogs": (school: "Montana-Western", abbr: "MWST"),
    "morehead state": (school: "Morehead State", abbr: "MORE"),
    "morehead state eagles": (school: "Morehead State", abbr: "MORE"),
    "morgan state": (school: "Morgan State", abbr: "MORG"),
    "morgan state bears": (school: "Morgan State", abbr: "MORG"),
    "mount st joseph": (school: "Mount St. Joseph", abbr: "MTS"),
    "mount st joseph lions": (school: "Mount St. Joseph", abbr: "MTS"),
    "murray state": (school: "Murray State", abbr: "MUR"),
    "murray state racers": (school: "Murray State", abbr: "MUR"),
    "navy": (school: "Navy", abbr: "NAVY"),
    "navy midshipmen": (school: "Navy", abbr: "NAVY"),
    "nc state": (school: "NC State", abbr: "NCSU"),
    "nc state wolfpack": (school: "NC State", abbr: "NCSU"),
    "nc wesleyan": (school: "NC Wesleyan", abbr: "NOR"),
    "nc wesleyan battling bishops": (school: "NC Wesleyan", abbr: "NOR"),
    "nebraska": (school: "Nebraska", abbr: "NEB"),
    "nebraska cornhuskers": (school: "Nebraska", abbr: "NEB"),
    "nebraskakearney": (school: "Nebraska-Kearney", abbr: "NEB"),
    "nebraskakearney lopers": (school: "Nebraska-Kearney", abbr: "NEB"),
    "nevada": (school: "Nevada", abbr: "NEV"),
    "nevada wolf pack": (school: "Nevada", abbr: "NEV"),
    "new hampshire": (school: "New Hampshire", abbr: "UNH"),
    "new hampshire wildcats": (school: "New Hampshire", abbr: "UNH"),
    "new haven": (school: "New Haven", abbr: "NHVN"),
    "new haven chargers": (school: "New Haven", abbr: "NHVN"),
    "new mexico": (school: "New Mexico", abbr: "UNM"),
    "new mexico highlands": (school: "New Mexico Highlands", abbr: "NMH"),
    "new mexico highlands cowboys": (school: "New Mexico Highlands", abbr: "NMH"),
    "new mexico lobos": (school: "New Mexico", abbr: "UNM"),
    "new mexico state": (school: "New Mexico State", abbr: "NMSU"),
    "new mexico state aggies": (school: "New Mexico State", abbr: "NMSU"),
    "nicholls": (school: "Nicholls", abbr: "NICH"),
    "nicholls colonels": (school: "Nicholls", abbr: "NICH"),
    "norfolk state": (school: "Norfolk State", abbr: "NORF"),
    "norfolk state spartans": (school: "Norfolk State", abbr: "NORF"),
    "north alabama": (school: "North Alabama", abbr: "UNA"),
    "north alabama lions": (school: "North Alabama", abbr: "UNA"),
    "north american university": (school: "North American University", abbr: "NAMERICAN"),
    "north american university stallions": (school: "North American University", abbr: "NAMERICAN"),
    "north carolina": (school: "North Carolina", abbr: "UNC"),
    "north carolina a&t": (school: "North Carolina A&T", abbr: "NCAT"),
    "north carolina a&t aggies": (school: "North Carolina A&T", abbr: "NCAT"),
    "north carolina central": (school: "North Carolina Central", abbr: "NCCU"),
    "north carolina central eagles": (school: "North Carolina Central", abbr: "NCCU"),
    "north carolina tar heels": (school: "North Carolina", abbr: "UNC"),
    "north dakota": (school: "North Dakota", abbr: "UND"),
    "north dakota fighting hawks": (school: "North Dakota", abbr: "UND"),
    "north dakota state": (school: "North Dakota State", abbr: "NDSU"),
    "north dakota state bison": (school: "North Dakota State", abbr: "NDSU"),
    "north texas": (school: "North Texas", abbr: "UNT"),
    "north texas mean green": (school: "North Texas", abbr: "UNT"),
    "northeastern": (school: "Northeastern", abbr: "NE"),
    "northeastern huskies": (school: "Northeastern", abbr: "NE"),
    "northeastern state": (school: "Northeastern State", abbr: "NEO"),
    "northeastern state riverhawks": (school: "Northeastern State", abbr: "NEO"),
    "northern arizona": (school: "Northern Arizona", abbr: "NAU"),
    "northern arizona lumberjacks": (school: "Northern Arizona", abbr: "NAU"),
    "northern colorado": (school: "Northern Colorado", abbr: "UNCO"),
    "northern colorado bears": (school: "Northern Colorado", abbr: "UNCO"),
    "northern illinois": (school: "Northern Illinois", abbr: "NIU"),
    "northern illinois huskies": (school: "Northern Illinois", abbr: "NIU"),
    "northern iowa": (school: "Northern Iowa", abbr: "UNI"),
    "northern iowa panthers": (school: "Northern Iowa", abbr: "UNI"),
    "northern michigan": (school: "Northern Michigan", abbr: "NMI"),
    "northern michigan wildcats": (school: "Northern Michigan", abbr: "NMI"),
    "northern state": (school: "Northern State", abbr: "NSU"),
    "northern state wolves": (school: "Northern State", abbr: "NSU"),
    "northwestern": (school: "Northwestern", abbr: "NU"),
    "northwestern (ia)": (school: "Northwestern (IA)", abbr: "NAD"),
    "northwestern (ia) nw college iowa": (school: "Northwestern (IA)", abbr: "NAD"),
    "northwestern oklahoma state": (school: "Northwestern Oklahoma State", abbr: "NWO"),
    "northwestern oklahoma state rangers": (school: "Northwestern Oklahoma State", abbr: "NWO"),
    "northwestern state": (school: "Northwestern State", abbr: "NWST"),
    "northwestern state demons": (school: "Northwestern State", abbr: "NWST"),
    "northwestern wildcats": (school: "Northwestern", abbr: "NU"),
    "notre dame": (school: "Notre Dame", abbr: "ND"),
    "notre dame college": (school: "Notre Dame College", abbr: "NOT"),
    "notre dame college blue falcons": (school: "Notre Dame College", abbr: "NOT"),
    "notre dame fighting irish": (school: "Notre Dame", abbr: "ND"),
    "ohio": (school: "Ohio", abbr: "OHIO"),
    "ohio bobcats": (school: "Ohio", abbr: "OHIO"),
    "ohio dominican": (school: "Ohio Dominican", abbr: "OHDM"),
    "ohio dominican panthers": (school: "Ohio Dominican", abbr: "OHDM"),
    "ohio state": (school: "Ohio State", abbr: "OSU"),
    "ohio state buckeyes": (school: "Ohio State", abbr: "OSU"),
    "ok panhandle st": (school: "OK Panhandle St", abbr: "OKP"),
    "ok panhandle st aggies": (school: "OK Panhandle St", abbr: "OKP"),
    "oklahoma": (school: "Oklahoma", abbr: "OU"),
    "oklahoma baptist": (school: "Oklahoma Baptist", abbr: "OB"),
    "oklahoma baptist bison": (school: "Oklahoma Baptist", abbr: "OB"),
    "oklahoma sooners": (school: "Oklahoma", abbr: "OU"),
    "oklahoma state": (school: "Oklahoma State", abbr: "OKST"),
    "oklahoma state cowboys": (school: "Oklahoma State", abbr: "OKST"),
    "old dominion": (school: "Old Dominion", abbr: "ODU"),
    "old dominion monarchs": (school: "Old Dominion", abbr: "ODU"),
    "ole miss": (school: "Ole Miss", abbr: "MISS"),
    "ole miss rebels": (school: "Ole Miss", abbr: "MISS"),
    "oregon": (school: "Oregon", abbr: "ORE"),
    "oregon ducks": (school: "Oregon", abbr: "ORE"),
    "oregon state": (school: "Oregon State", abbr: "ORST"),
    "oregon state beavers": (school: "Oregon State", abbr: "ORST"),
    "ouachita baptist": (school: "Ouachita Baptist", abbr: "OUA"),
    "ouachita baptist tigers": (school: "Ouachita Baptist", abbr: "OUA"),
    "pace": (school: "Pace", abbr: "PAC"),
    "pace setters": (school: "Pace", abbr: "PAC"),
    "paul quinn": (school: "Paul Quinn", abbr: "PPN"),
    "paul quinn tigers": (school: "Paul Quinn", abbr: "PPN"),
    "penn state": (school: "Penn State", abbr: "PSU"),
    "penn state nittany lions": (school: "Penn State", abbr: "PSU"),
    "pennsylvania": (school: "Pennsylvania", abbr: "PENN"),
    "pennsylvania quakers": (school: "Pennsylvania", abbr: "PENN"),
    "pennwest california": (school: "PennWest California", abbr: "PWC"),
    "pennwest california vulcans": (school: "PennWest California", abbr: "PWC"),
    "pikeville": (school: "Pikeville", abbr: "PIKEV"),
    "pikeville bears": (school: "Pikeville", abbr: "PIKEV"),
    "pittsburg state": (school: "Pittsburg State", abbr: "PIT"),
    "pittsburg state gorillas": (school: "Pittsburg State", abbr: "PIT"),
    "pittsburgh": (school: "Pittsburgh", abbr: "PITT"),
    "pittsburgh panthers": (school: "Pittsburgh", abbr: "PITT"),
    "point university": (school: "Point University", abbr: "POINT"),
    "point university point": (school: "Point University", abbr: "POINT"),
    "portland state": (school: "Portland State", abbr: "PRST"),
    "portland state vikings": (school: "Portland State", abbr: "PRST"),
    "post university": (school: "Post University", abbr: "POST"),
    "post university eagles": (school: "Post University", abbr: "POST"),
    "prairie view a&m": (school: "Prairie View A&M", abbr: "PV"),
    "prairie view a&m panthers": (school: "Prairie View A&M", abbr: "PV"),
    "presbyterian": (school: "Presbyterian", abbr: "PRES"),
    "presbyterian blue hose": (school: "Presbyterian", abbr: "PRES"),
    "princeton": (school: "Princeton", abbr: "PRIN"),
    "princeton tigers": (school: "Princeton", abbr: "PRIN"),
    "purdue": (school: "Purdue", abbr: "PUR"),
    "purdue boilermakers": (school: "Purdue", abbr: "PUR"),
    "rhode island": (school: "Rhode Island", abbr: "URI"),
    "rhode island rams": (school: "Rhode Island", abbr: "URI"),
    "rhodes college": (school: "Rhodes College", abbr: "RHO"),
    "rhodes college lynx": (school: "Rhodes College", abbr: "RHO"),
    "rice": (school: "Rice", abbr: "RICE"),
    "rice owls": (school: "Rice", abbr: "RICE"),
    "richmond": (school: "Richmond", abbr: "RICH"),
    "richmond spiders": (school: "Richmond", abbr: "RICH"),
    "rio grande": (school: "Rio Grande", abbr: "RIO"),
    "rio grande red storm": (school: "Rio Grande", abbr: "RIO"),
    "robert morris": (school: "Robert Morris", abbr: "RMU"),
    "robert morris colonials": (school: "Robert Morris", abbr: "RMU"),
    "roosevelt": (school: "Roosevelt", abbr: "ROOSE"),
    "roosevelt lakers": (school: "Roosevelt", abbr: "ROOSE"),
    "rowan": (school: "Rowan", abbr: "ROW"),
    "rowan profs": (school: "Rowan", abbr: "ROW"),
    "rutgers": (school: "Rutgers", abbr: "RUTG"),
    "rutgers scarlet knights": (school: "Rutgers", abbr: "RUTG"),
    "sacramento state": (school: "Sacramento State", abbr: "SAC"),
    "sacramento state hornets": (school: "Sacramento State", abbr: "SAC"),
    "sacred heart": (school: "Sacred Heart", abbr: "SHU"),
    "sacred heart pioneers": (school: "Sacred Heart", abbr: "SHU"),
    "saginaw valley state": (school: "Saginaw Valley State", abbr: "SVS"),
    "saginaw valley state cardinals": (school: "Saginaw Valley State", abbr: "SVS"),
    "saint francis": (school: "Saint Francis", abbr: "SFPA"),
    "saint francis red flash": (school: "Saint Francis", abbr: "SFPA"),
    "salve regina": (school: "Salve Regina", abbr: "SAL"),
    "salve regina seahawks": (school: "Salve Regina", abbr: "SAL"),
    "sam houston": (school: "Sam Houston", abbr: "SHSU"),
    "sam houston bearkats": (school: "Sam Houston", abbr: "SHSU"),
    "samford": (school: "Samford", abbr: "SAM"),
    "samford bulldogs": (school: "Samford", abbr: "SAM"),
    "san diego": (school: "San Diego", abbr: "USD"),
    "san diego state": (school: "San Diego State", abbr: "SDSU"),
    "san diego state aztecs": (school: "San Diego State", abbr: "SDSU"),
    "san diego toreros": (school: "San Diego", abbr: "USD"),
    "san jose state": (school: "San José State", abbr: "SJSU"),
    "san jose state spartans": (school: "San José State", abbr: "SJSU"),
    "se louisiana": (school: "SE Louisiana", abbr: "SELA"),
    "se louisiana lions": (school: "SE Louisiana", abbr: "SELA"),
    "shaw": (school: "Shaw", abbr: "SHA"),
    "shaw bears": (school: "Shaw", abbr: "SHA"),
    "shorter": (school: "Shorter", abbr: "SHO"),
    "shorter hawks": (school: "Shorter", abbr: "SHO"),
    "simon fraser": (school: "Simon Fraser", abbr: "SIM"),
    "simon fraser clansmen": (school: "Simon Fraser", abbr: "SIM"),
    "slippery rock": (school: "Slippery Rock", abbr: "SRU"),
    "slippery rock the rock": (school: "Slippery Rock", abbr: "SRU"),
    "smu": (school: "SMU", abbr: "SMU"),
    "smu mustangs": (school: "SMU", abbr: "SMU"),
    "south alabama": (school: "South Alabama", abbr: "USA"),
    "south alabama jaguars": (school: "South Alabama", abbr: "USA"),
    "south carolina": (school: "South Carolina", abbr: "SC"),
    "south carolina gamecocks": (school: "South Carolina", abbr: "SC"),
    "south carolina state": (school: "South Carolina State", abbr: "SCST"),
    "south carolina state bulldogs": (school: "South Carolina State", abbr: "SCST"),
    "south dakota": (school: "South Dakota", abbr: "SDAK"),
    "south dakota coyotes": (school: "South Dakota", abbr: "SDAK"),
    "south dakota mines": (school: "South Dakota Mines", abbr: "SDA"),
    "south dakota mines hardrockers": (school: "South Dakota Mines", abbr: "SDA"),
    "south dakota state": (school: "South Dakota State", abbr: "SDST"),
    "south dakota state jackrabbits": (school: "South Dakota State", abbr: "SDST"),
    "south florida": (school: "South Florida", abbr: "USF"),
    "south florida bulls": (school: "South Florida", abbr: "USF"),
    "southeast missouri state": (school: "Southeast Missouri State", abbr: "SEMO"),
    "southeast missouri state redhawks": (school: "Southeast Missouri State", abbr: "SEMO"),
    "southeastern oklahoma": (school: "Southeastern Oklahoma", abbr: "SEOS"),
    "southeastern oklahoma savage storm": (school: "Southeastern Oklahoma", abbr: "SEOS"),
    "southern": (school: "Southern", abbr: "SOU"),
    "southern arkansas": (school: "Southern Arkansas", abbr: "SOU"),
    "southern arkansas muleriders": (school: "Southern Arkansas", abbr: "SOU"),
    "southern connecticut state": (school: "Southern Connecticut State", abbr: "SOU"),
    "southern connecticut state owls": (school: "Southern Connecticut State", abbr: "SOU"),
    "southern illinois": (school: "Southern Illinois", abbr: "SIU"),
    "southern illinois salukis": (school: "Southern Illinois", abbr: "SIU"),
    "southern jaguars": (school: "Southern", abbr: "SOU"),
    "southern miss": (school: "Southern Miss", abbr: "USM"),
    "southern miss golden eagles": (school: "Southern Miss", abbr: "USM"),
    "southern oregon": (school: "Southern Oregon", abbr: "SOU"),
    "southern oregon raiders": (school: "Southern Oregon", abbr: "SOU"),
    "southern utah": (school: "Southern Utah", abbr: "SUU"),
    "southern utah thunderbirds": (school: "Southern Utah", abbr: "SUU"),
    "southern virginia": (school: "Southern Virginia", abbr: "SVA"),
    "southern virginia knights": (school: "Southern Virginia", abbr: "SVA"),
    "southwest baptist": (school: "Southwest Baptist", abbr: "SWB"),
    "southwest baptist bearcats": (school: "Southwest Baptist", abbr: "SWB"),
    "southwestern college": (school: "Southwestern College", abbr: "SWC"),
    "southwestern college moundbuilders": (school: "Southwestern College", abbr: "SWC"),
    "southwestern oklahoma": (school: "Southwestern Oklahoma", abbr: "SWO"),
    "southwestern oklahoma bulldogs": (school: "Southwestern Oklahoma", abbr: "SWO"),
    "st andrews": (school: "St. Andrews", abbr: "ST. A"),
    "st andrews knights": (school: "St. Andrews", abbr: "ST. A"),
    "st anselm": (school: "St. Anselm", abbr: "STA"),
    "st anselm hawks": (school: "St. Anselm", abbr: "STA"),
    "st augustines": (school: "St. Augustine's", abbr: "STA"),
    "st augustines falcons": (school: "St. Augustine's", abbr: "STA"),
    "st cloud state": (school: "St. Cloud State", abbr: "STC"),
    "st cloud state huskies": (school: "St. Cloud State", abbr: "STC"),
    "st francis (in)": (school: "St. Francis (IN)", abbr: "SBP"),
    "st francis (in) cougars": (school: "St. Francis (IN)", abbr: "SBP"),
    "st francis illinois": (school: "St Francis Illinois", abbr: "SFIL"),
    "st francis illinois fighting saints": (school: "St Francis Illinois", abbr: "SFIL"),
    "st josephs (in)": (school: "St. Joseph's (IN)", abbr: "STJ"),
    "st josephs (in) pumas": (school: "St. Joseph's (IN)", abbr: "STJ"),
    "st peters": (school: "St. Peter's", abbr: "SPU"),
    "st peters peacocks": (school: "St. Peter's", abbr: "SPU"),
    "st thomasminnesota": (school: "St. Thomas-Minnesota", abbr: "STMN"),
    "st thomasminnesota tommies": (school: "St. Thomas-Minnesota", abbr: "STMN"),
    "st xavier (il)": (school: "St. Xavier (IL)", abbr: "STX"),
    "st xavier (il) cougars": (school: "St. Xavier (IL)", abbr: "STX"),
    "stanford": (school: "Stanford", abbr: "STAN"),
    "stanford cardinal": (school: "Stanford", abbr: "STAN"),
    "stephen f austin": (school: "Stephen F. Austin", abbr: "SFA"),
    "stephen f austin lumberjacks": (school: "Stephen F. Austin", abbr: "SFA"),
    "stetson": (school: "Stetson", abbr: "STET"),
    "stetson hatters": (school: "Stetson", abbr: "STET"),
    "stillman": (school: "Stillman", abbr: "STI"),
    "stillman tigers": (school: "Stillman", abbr: "STI"),
    "stonehill": (school: "Stonehill", abbr: "STO"),
    "stonehill skyhawks": (school: "Stonehill", abbr: "STO"),
    "stony brook": (school: "Stony Brook", abbr: "STBK"),
    "stony brook seawolves": (school: "Stony Brook", abbr: "STBK"),
    "sul ross state": (school: "Sul Ross State", abbr: "SROS"),
    "sul ross state lobos": (school: "Sul Ross State", abbr: "SROS"),
    "suny maritime": (school: "SUNY Maritime", abbr: "MAR"),
    "suny maritime privateers": (school: "SUNY Maritime", abbr: "MAR"),
    "syracuse": (school: "Syracuse", abbr: "SYR"),
    "syracuse orange": (school: "Syracuse", abbr: "SYR"),
    "tarleton state": (school: "Tarleton State", abbr: "TAR"),
    "tarleton state texans": (school: "Tarleton State", abbr: "TAR"),
    "taylor": (school: "Taylor", abbr: "TAY"),
    "taylor trojans": (school: "Taylor", abbr: "TAY"),
    "tbd": (school: "TBD", abbr: "TBD"),
    "tcu": (school: "TCU", abbr: "TCU"),
    "tcu horned frogs": (school: "TCU", abbr: "TCU"),
    "temple": (school: "Temple", abbr: "TEM"),
    "temple owls": (school: "Temple", abbr: "TEM"),
    "tennessee": (school: "Tennessee", abbr: "TENN"),
    "tennessee state": (school: "Tennessee State", abbr: "TNST"),
    "tennessee state tigers": (school: "Tennessee State", abbr: "TNST"),
    "tennessee tech": (school: "Tennessee Tech", abbr: "TNTC"),
    "tennessee tech golden eagles": (school: "Tennessee Tech", abbr: "TNTC"),
    "tennessee volunteers": (school: "Tennessee", abbr: "TENN"),
    "texas": (school: "Texas", abbr: "TEX"),
    "texas a&m": (school: "Texas A&M", abbr: "TA&M"),
    "texas a&m aggies": (school: "Texas A&M", abbr: "TA&M"),
    "texas a&mkingsville": (school: "Texas A&M-Kingsville", abbr: "TXA"),
    "texas a&mkingsville javelinas": (school: "Texas A&M-Kingsville", abbr: "TXA"),
    "texas college": (school: "Texas College", abbr: "TXCL"),
    "texas college steers": (school: "Texas College", abbr: "TXCL"),
    "texas longhorns": (school: "Texas", abbr: "TEX"),
    "texas southern": (school: "Texas Southern", abbr: "TXSO"),
    "texas southern tigers": (school: "Texas Southern", abbr: "TXSO"),
    "texas state": (school: "Texas State", abbr: "TXST"),
    "texas state bobcats": (school: "Texas State", abbr: "TXST"),
    "texas tech": (school: "Texas Tech", abbr: "TTU"),
    "texas tech red raiders": (school: "Texas Tech", abbr: "TTU"),
    "texas wesleyan": (school: "Texas Wesleyan", abbr: "TXWE"),
    "texas wesleyan rams": (school: "Texas Wesleyan", abbr: "TXWE"),
    "the citadel": (school: "The Citadel", abbr: "CIT"),
    "the citadel bulldogs": (school: "The Citadel", abbr: "CIT"),
    "thomas more college": (school: "Thomas More College", abbr: "THO"),
    "thomas more college saints": (school: "Thomas More College", abbr: "THO"),
    "tiffin": (school: "Tiffin", abbr: "TIF"),
    "tiffin dragons": (school: "Tiffin", abbr: "TIF"),
    "toledo": (school: "Toledo", abbr: "TOL"),
    "toledo rockets": (school: "Toledo", abbr: "TOL"),
    "towson": (school: "Towson", abbr: "TOW"),
    "towson tigers": (school: "Towson", abbr: "TOW"),
    "trinity international (il)": (school: "Trinity International (IL)", abbr: "TRN"),
    "trinity international (il) trojans": (school: "Trinity International (IL)", abbr: "TRN"),
    "troy": (school: "Troy", abbr: "TROY"),
    "troy trojans": (school: "Troy", abbr: "TROY"),
    "truman state": (school: "Truman State", abbr: "TRU"),
    "truman state bulldogs": (school: "Truman State", abbr: "TRU"),
    "tulane": (school: "Tulane", abbr: "TULN"),
    "tulane green wave": (school: "Tulane", abbr: "TULN"),
    "tulsa": (school: "Tulsa", abbr: "TLSA"),
    "tulsa golden hurricane": (school: "Tulsa", abbr: "TLSA"),
    "tusculum": (school: "Tusculum", abbr: "TUS"),
    "tusculum pioneers": (school: "Tusculum", abbr: "TUS"),
    "uab": (school: "UAB", abbr: "UAB"),
    "uab blazers": (school: "UAB", abbr: "UAB"),
    "ualbany": (school: "UAlbany", abbr: "UALB"),
    "ualbany great danes": (school: "UAlbany", abbr: "UALB"),
    "uc davis": (school: "UC Davis", abbr: "UCD"),
    "uc davis aggies": (school: "UC Davis", abbr: "UCD"),
    "ucf": (school: "UCF", abbr: "UCF"),
    "ucf knights": (school: "UCF", abbr: "UCF"),
    "ucla": (school: "UCLA", abbr: "UCLA"),
    "ucla bruins": (school: "UCLA", abbr: "UCLA"),
    "uconn": (school: "UConn", abbr: "CONN"),
    "uconn huskies": (school: "UConn", abbr: "CONN"),
    "uftl": (school: "UFTL", abbr: "UFTL"),
    "uftl eagles": (school: "UFTL", abbr: "UFTL"),
    "ul monroe": (school: "UL Monroe", abbr: "ULM"),
    "ul monroe warhawks": (school: "UL Monroe", abbr: "ULM"),
    "unc pembroke": (school: "UNC Pembroke", abbr: "NCP"),
    "unc pembroke braves": (school: "UNC Pembroke", abbr: "NCP"),
    "union college": (school: "Union College", abbr: "UNI"),
    "union college dutchmen": (school: "Union College", abbr: "UNI"),
    "university of faith": (school: "University of Faith", abbr: "UFFL"),
    "university of faith glory eagles": (school: "University of Faith", abbr: "UFFL"),
    "unlv": (school: "UNLV", abbr: "UNLV"),
    "unlv rebels": (school: "UNLV", abbr: "UNLV"),
    "upper iowa university": (school: "Upper Iowa University", abbr: "UPP"),
    "upper iowa university peacocks": (school: "Upper Iowa University", abbr: "UPP"),
    "urbana": (school: "Urbana", abbr: "URB"),
    "urbana blue knights": (school: "Urbana", abbr: "URB"),
    "usc": (school: "USC", abbr: "USC"),
    "usc trojans": (school: "USC", abbr: "USC"),
    "ut martin": (school: "UT Martin", abbr: "UTM"),
    "ut martin skyhawks": (school: "UT Martin", abbr: "UTM"),
    "ut permian basin": (school: "UT Permian Basin", abbr: "UTPB"),
    "ut permian basin falcons": (school: "UT Permian Basin", abbr: "UTPB"),
    "ut rio grande valley": (school: "UT Rio Grande Valley", abbr: "RGV"),
    "ut rio grande valley vaqueros": (school: "UT Rio Grande Valley", abbr: "RGV"),
    "utah": (school: "Utah", abbr: "UTAH"),
    "utah state": (school: "Utah State", abbr: "USU"),
    "utah state aggies": (school: "Utah State", abbr: "USU"),
    "utah tech": (school: "Utah Tech", abbr: "UTU"),
    "utah tech trailblazers": (school: "Utah Tech", abbr: "UTU"),
    "utah utes": (school: "Utah", abbr: "UTAH"),
    "utep": (school: "UTEP", abbr: "UTEP"),
    "utep miners": (school: "UTEP", abbr: "UTEP"),
    "utsa": (school: "UTSA", abbr: "UTSA"),
    "utsa roadrunners": (school: "UTSA", abbr: "UTSA"),
    "uvawise": (school: "UVA-Wise", abbr: "VAW"),
    "uvawise highland cavaliers": (school: "UVA-Wise", abbr: "VAW"),
    "uwoshkosh": (school: "UW-Oshkosh", abbr: "WIS"),
    "uwoshkosh titans": (school: "UW-Oshkosh", abbr: "WIS"),
    "valdosta state": (school: "Valdosta State", abbr: "VAL"),
    "valdosta state blazers": (school: "Valdosta State", abbr: "VAL"),
    "valparaiso": (school: "Valparaiso", abbr: "VAL"),
    "valparaiso beacons": (school: "Valparaiso", abbr: "VAL"),
    "vanderbilt": (school: "Vanderbilt", abbr: "VAN"),
    "vanderbilt commodores": (school: "Vanderbilt", abbr: "VAN"),
    "villanova": (school: "Villanova", abbr: "VILL"),
    "villanova wildcats": (school: "Villanova", abbr: "VILL"),
    "virginia": (school: "Virginia", abbr: "UVA"),
    "virginia cavaliers": (school: "Virginia", abbr: "UVA"),
    "virginia state": (school: "Virginia State", abbr: "VIR"),
    "virginia state trojans": (school: "Virginia State", abbr: "VIR"),
    "virginia tech": (school: "Virginia Tech", abbr: "VT"),
    "virginia tech hokies": (school: "Virginia Tech", abbr: "VT"),
    "virginia university of lynchburg": (school: "Virginia University Of Lynchburg", abbr: "VIRLYN"),
    "virginia university of lynchburg dragons": (school: "Virginia University Of Lynchburg", abbr: "VIRLYN"),
    "vmi": (school: "VMI", abbr: "VMI"),
    "vmi keydets": (school: "VMI", abbr: "VMI"),
    "wabash college": (school: "Wabash College", abbr: "WAB"),
    "wabash college little giants": (school: "Wabash College", abbr: "WAB"),
    "wagner": (school: "Wagner", abbr: "WAG"),
    "wagner seahawks": (school: "Wagner", abbr: "WAG"),
    "wake forest": (school: "Wake Forest", abbr: "WAKE"),
    "wake forest demon deacons": (school: "Wake Forest", abbr: "WAKE"),
    "waldorf": (school: "Waldorf", abbr: "WAL"),
    "waldorf warriors": (school: "Waldorf", abbr: "WAL"),
    "walsh": (school: "Walsh", abbr: "WALSH"),
    "walsh cavaliers": (school: "Walsh", abbr: "WALSH"),
    "warner university": (school: "Warner University", abbr: "WARNE"),
    "warner university royals": (school: "Warner University", abbr: "WARNE"),
    "washburn": (school: "Washburn", abbr: "WAS"),
    "washburn ichabods": (school: "Washburn", abbr: "WAS"),
    "washington": (school: "Washington", abbr: "WASH"),
    "washington huskies": (school: "Washington", abbr: "WASH"),
    "washington state": (school: "Washington State", abbr: "WSU"),
    "washington state cougars": (school: "Washington State", abbr: "WSU"),
    "wayland baptist": (school: "Wayland Baptist", abbr: "WAYLAND"),
    "wayland baptist pioneers": (school: "Wayland Baptist", abbr: "WAYLAND"),
    "webber international": (school: "Webber International", abbr: "WEBB"),
    "webber international warriors": (school: "Webber International", abbr: "WEBB"),
    "weber state": (school: "Weber State", abbr: "WEB"),
    "weber state wildcats": (school: "Weber State", abbr: "WEB"),
    "wesley college": (school: "Wesley College", abbr: "WES"),
    "wesley college wolverines": (school: "Wesley College", abbr: "WES"),
    "west alabama": (school: "West Alabama", abbr: "WES"),
    "west alabama tigers": (school: "West Alabama", abbr: "WES"),
    "west chester": (school: "West Chester", abbr: "WES"),
    "west chester golden rams": (school: "West Chester", abbr: "WES"),
    "west florida": (school: "West Florida", abbr: "WFLA"),
    "west florida argonauts": (school: "West Florida", abbr: "WFLA"),
    "west georgia": (school: "West Georgia", abbr: "WGA"),
    "west georgia wolves": (school: "West Georgia", abbr: "WGA"),
    "west liberty": (school: "West Liberty", abbr: "WES"),
    "west liberty hilltoppers": (school: "West Liberty", abbr: "WES"),
    "west texas a&m": (school: "West Texas A&M", abbr: "WES"),
    "west texas a&m buffaloes": (school: "West Texas A&M", abbr: "WES"),
    "west virginia": (school: "West Virginia", abbr: "WVU"),
    "west virginia institute of tech": (school: "West Virginia Institute Of Tech", abbr: "WVT"),
    "west virginia institute of tech golden bears": (school: "West Virginia Institute Of Tech", abbr: "WVT"),
    "west virginia mountaineers": (school: "West Virginia", abbr: "WVU"),
    "western carolina": (school: "Western Carolina", abbr: "WCU"),
    "western carolina catamounts": (school: "Western Carolina", abbr: "WCU"),
    "western connecticut state": (school: "Western Connecticut State", abbr: "WES"),
    "western connecticut state colonials": (school: "Western Connecticut State", abbr: "WES"),
    "western illinois": (school: "Western Illinois", abbr: "WIU"),
    "western illinois leathernecks": (school: "Western Illinois", abbr: "WIU"),
    "western kentucky": (school: "Western Kentucky", abbr: "WKU"),
    "western kentucky hilltoppers": (school: "Western Kentucky", abbr: "WKU"),
    "western michigan": (school: "Western Michigan", abbr: "WMU"),
    "western michigan broncos": (school: "Western Michigan", abbr: "WMU"),
    "western new england": (school: "Western New England", abbr: "WES"),
    "western new england golden bears": (school: "Western New England", abbr: "WES"),
    "western new mexico": (school: "Western New Mexico", abbr: "WES"),
    "western new mexico mustangs": (school: "Western New Mexico", abbr: "WES"),
    "western oregon": (school: "Western Oregon", abbr: "WORE"),
    "western oregon wolves": (school: "Western Oregon", abbr: "WORE"),
    "western state": (school: "Western State", abbr: "WES"),
    "western state mountaineers": (school: "Western State", abbr: "WES"),
    "western washington": (school: "Western Washington", abbr: "WES"),
    "western washington vikings": (school: "Western Washington", abbr: "WES"),
    "wheeling": (school: "Wheeling", abbr: "WHEE"),
    "wheeling cardinals": (school: "Wheeling", abbr: "WHEE"),
    "willamette": (school: "Willamette", abbr: "WIL"),
    "willamette bearcats": (school: "Willamette", abbr: "WIL"),
    "william & mary": (school: "William & Mary", abbr: "W&M"),
    "william & mary tribe": (school: "William & Mary", abbr: "W&M"),
    "william jewell college": (school: "William Jewell College", abbr: "WJC"),
    "william jewell college cardinals": (school: "William Jewell College", abbr: "WJC"),
    "william penn": (school: "William Penn", abbr: "WIL"),
    "william penn statesmen": (school: "William Penn", abbr: "WIL"),
    "wingate": (school: "Wingate", abbr: "WIN"),
    "wingate bulldogs": (school: "Wingate", abbr: "WIN"),
    "winona state": (school: "Winona State", abbr: "WIN"),
    "winona state warriors": (school: "Winona State", abbr: "WIN"),
    "winstonsalem": (school: "Winston-Salem", abbr: "WSSU"),
    "winstonsalem rams": (school: "Winston-Salem", abbr: "WSSU"),
    "wisconsin": (school: "Wisconsin", abbr: "WIS"),
    "wisconsin badgers": (school: "Wisconsin", abbr: "WIS"),
    "wisconsin lutheran": (school: "Wisconsin Lutheran", abbr: "WIS"),
    "wisconsin lutheran warriors": (school: "Wisconsin Lutheran", abbr: "WIS"),
    "wisconsinplatteville": (school: "Wisconsin-Platteville", abbr: "WIS"),
    "wisconsinplatteville pioneers": (school: "Wisconsin-Platteville", abbr: "WIS"),
    "wisconsinstevens point": (school: "Wisconsin-Stevens Point", abbr: "WIS"),
    "wisconsinstevens point pointers": (school: "Wisconsin-Stevens Point", abbr: "WIS"),
    "wittenberg": (school: "Wittenberg", abbr: "WITTEN"),
    "wittenberg tigers": (school: "Wittenberg", abbr: "WITTEN"),
    "wofford": (school: "Wofford", abbr: "WOF"),
    "wofford terriers": (school: "Wofford", abbr: "WOF"),
    "wv state": (school: "WV State", abbr: "WES"),
    "wv state yellow jackets": (school: "WV State", abbr: "WES"),
    "wv wesleyan": (school: "WV Wesleyan", abbr: "WVW"),
    "wv wesleyan bobcats": (school: "WV Wesleyan", abbr: "WVW"),
    "wyoming": (school: "Wyoming", abbr: "WYO"),
    "wyoming cowboys": (school: "Wyoming", abbr: "WYO"),
    "yale": (school: "Yale", abbr: "YALE"),
    "yale bulldogs": (school: "Yale", abbr: "YALE"),
    "youngstown state": (school: "Youngstown State", abbr: "YSU"),
    "youngstown state penguins": (school: "Youngstown State", abbr: "YSU"),
    ]

    /// The app's own normalizer — must match the generator's `norm`.
    static func key(_ name: String) -> String {
        let folded = name.folding(options: [.diacriticInsensitive], locale: Locale(identifier: "en_US_POSIX")).lowercased()
        let kept = folded.unicodeScalars.filter { scalar in
            CharacterSet.alphanumerics.contains(scalar) || scalar == " " || scalar == "&" || scalar == "(" || scalar == ")"
        }
        return String(String.UnicodeScalarView(kept)).split(separator: " ").joined(separator: " ")
    }

    /// "San José State Spartans" → "San José State". nil when the school is
    /// not the provider's (an FCS opponent the feed spells its own way).
    static func school(_ name: String) -> String? { byName[key(name)]?.school }

    /// "San José State Spartans" → "SJSU".
    static func abbreviation(_ name: String) -> String? { byName[key(name)]?.abbr }
}
