[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# API proxy for Perplexity to avoid CORS issues
[[redirects]]
  from = "/api/proxy/perplexity"
  to = "/.netlify/functions/perplexity-proxy"
  status = 200

# SPA redirect for client-side routing  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
